on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Wasm
        run: wasm-pack build

      - uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Build App
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Upload App
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./frontend/dist"
  deploy:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy
        uses: action/deploy-pages@v4
